### ISSUE TITLE
Unable to submit csr on windows

### ISSUE THREAD

**Issue by maxpavlov** [freddy36/StartSSL_API#2]
I've installed Python 2.7 and all of the listed dependencies on windows. I've adjusted configuration file and was able to successully list available certificates from my account via `python startssl.py certs`.

I've created a key without a password via command:
`openssl genrsa -out ./mail.maxpavlov.com/mail.maxpavlov.com.key 2048`

And was able to create a certificate signing request with it via call to:
`openssl req -new -sha256 -key ./mail.maxpavlov.com/mail.maxpavlov.com.key -out ./mail.maxpavlov.com/mail.maxpavlov.com.csr`

Now with that CSR file I called:
`startssl.py csr ./mail.maxpavlov.com/mail.maxpavlov.com.csr ./mail.maxpavlov.com/mail.maxpavlov.com.csr`

It is not clear what those two params are, so I used the same csr as both params. The error I got was:

> C:\Users\username\Documents\GitHub\StartSSL_API>startssl.py csr ./mail.maxpavlov.com/mail.maxpavlov.com.csr ./mail.maxpavlov.com/mail.maxpavlov.com.csr
> Submitting ./mail.maxpavlov.com/mail.maxpavlov.com.csr
> Submission failed:
> Traceback (most recent call last):
>   File "C:\Users\mapa\Documents\GitHub\StartSSL_API\startssl.py", line 575, in <module>
>     certificate_id, common_name, subjects, cert = api.submit_certificate_request(profile=args.profile, csr=csr)
>   File "C:\Users\mapa\Documents\GitHub\StartSSL_API\startssl.py", line 403, in submit_certificate_request
>     assert profile in self.CERTIFICATE_PROFILES, "unknown profile"
> AttributeError: 'API' object has no attribute 'CERTIFICATE_PROFILES'
> 
> Submitting ./mail.maxpavlov.com/mail.maxpavlov.com.csr
> Submission failed:
> Traceback (most recent call last):
>   File "C:\Users\mapa\Documents\GitHub\StartSSL_API\startssl.py", line 575, in <module>
>     certificate_id, common_name, subjects, cert = api.submit_certificate_request(profile=args.profile, csr=csr)
>   File "C:\Users\mapa\Documents\GitHub\StartSSL_API\startssl.py", line 403, in submit_certificate_request
>     assert profile in self.CERTIFICATE_PROFILES, "unknown profile"
> AttributeError: 'API' object has no attribute 'CERTIFICATE_PROFILES'

Please assist to get this working. Thanks.

**Comment by maxpavlov** [comment]
I've investigated more. I think 
self.CERTIFICATE_PROFILES is never set to anything thus any request to csr will fail. The actual profile var value in my case is 'server'. The executing fails on line:
`assert profile in self.CERTIFICATE_PROFILES, "unknown profile"`

**Comment by maxpavlov** [comment]
Ok, I've updated the script to work with the current StartSSL site.
It's available [here at my fork](https://github.com/maxpavlov/StartSSL_API). 
I've reduced the steps at CSR though to only submit main domain and then subdomain and check if the correct code is returned. I don't retrieve the cert after it has been successfully submitted for generation.

**Comment by freddy36** [comment]
Hi,

I was on vacation. My version still wasn't completely updated (csr submission was missing) for the complete redesign of the StartSSL website earlier this year. Thank you for fixing it. I'll have a look at it and merge it.
